name: template_b2g_config
on: 
  workflow_dispatch:

# NEED  
# 1. secrets.GIT_ACCESS_TOKEN
# 2. secrets.RCLONE
# 3. device_name eg；onyx(oneplu x), bacon(oneplus one), phhgsi_arm64_a(phh's gsi) etc.
# 4. build_device_tag: eg: full-onyx-eng, full-bacon-userdebug etc.
# 5. repo_dispatches: https://api.github.com/repos/(you id)/(you repo name)/dispatches
# 6. android_source: 
#         remote soucre address: 
#          https://android.googlesource.com/platform/manifest -b android-10.0.0_r41
# for example:
env:
  GIT_ACCESS_TOKEN: ${{secrets.GIT_ACCESS_TOKEN}}
  device_name: gsi_b2g
  repo_dispatches: "https://api.github.com/ittat-store/build-actions/dispatches"
  b2g_source: "https://github.com/ittat/B2G"
  b2g_branch: "master"

jobs: 
  config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Action        
      run: |
        ./b2g/init/webhook.sh b2g_repack    
